# PID of current job: 546870
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "colu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "none", "F", 25)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "SpecNorm", "NULL", "ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PLSDA.CV(mSet, "L",3, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 72, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PlotHeatMap(mSet, "heatmap_0_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", "overview", T, T, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "column", "euclidean", "ward.D","bwm", "overview", T, T, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_2_", "png", 72, width=NA, "norm", "column", "euclidean", "average","bwm", "overview", T, T, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_3_", "png", 72, width=NA, "norm", "column", "euclidean", "complete","bwm", "overview", T, T, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_4_", "png", 72, width=NA, "norm", "column", "euclidean", "complete","bwm", "overview", F, T, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_5_", "png", 72, width=NA, "norm", "column", "euclidean", "complete","bwm", "overview", T, F, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_6_", "png", 72, width=NA, "norm", "column", "euclidean", "complete","bwm", "overview", F, F, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_7_", "png", 72, width=NA, "norm", "column", "euclidean", "average","bwm", "overview", F, F, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_8_", "png", 72, width=NA, "norm", "row", "euclidean", "average","bwm", "overview", F, F, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_9_", "png", 72, width=NA, "norm", "row", "euclidean", "average","bwm", "overview", F, F, NULL, T, T)
mSet<-PlotHeatMap(mSet, "heatmap_10_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", "overview", F, F, NULL, T, T)
mSet<-PlotHeatMap(mSet, "heatmap_11_", "png", 72, width=NA, "norm", "row", "correlation", "average","bwm", "overview", F, F, NULL, T, T)
mSet<-PlotHeatMap(mSet, "heatmap_12_", "png", 72, width=NA, "norm", "row", "correlation", "average","bwm", "overview", F, F, NULL, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_13_", "png", 72, width=NA, "norm", "row", "correlation", "average","bwm", "overview", F, F, NULL, T, T)
mSet<-PlotHeatMap(mSet, "heatmap_14_", "png", 72, width=NA, "norm", "column", "correlation", "average","bwm", "overview", F, F, NULL, T, T)
mSet<-PlotHeatMap(mSet, "heatmap_15_", "png", 72, width=NA, "norm", "none", "correlation", "average","bwm", "overview", F, F, NULL, T, T)
mSet<-PlotHeatMap(mSet, "heatmap_16_", "png", 72, width=NA, "norm", "row", "correlation", "average","bwm", "overview", F, F, NULL, T, T)
mSet<-PlotHeatMap(mSet, "heatmap_17_", "png", 72, width=NA, "norm", "none", "correlation", "average","bwm", "overview", F, F, NULL, T, T)
